### ISSUE TITLE
[Meta] UX redesign

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/openwapp#1]
Openwapp needs a design update to:
- Present the same UI elements the official clients have and users are familiar with.
- Have a Firefox OS flavour based on the Haida guidelines (Firefox OS 2.0+)

This issue will be used to track relevant issues trying to implement these changes and as discussion.
- [x] #4 Header color and integration
- [ ] #5 Conversation view spacing
- [ ] #6 Message view spacing
- [ ] #7 Image preview improvements
- [x] #13 Logo refresh
- [ ] #17 Color scheme and images, icons, fonts based on Firefox 2.0 haida
